#!/usr/bin/env bash
# This script lists files and prints part after first dash

for file in *; do
  name="${file#*-}"
  if [ "$name" != "$file" ]; then
    echo "$name"
  else
    echo "$file"
  fi
done

