#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code and displays them sorted by occurrence

awk 'NF >= 9 {print $1, $9}' access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'

