#!/usr/bin/env bash
# This script prints the time from 0:1 to 12:59

hour=0

while [ $hour -le 12 ]; do
    if [ $hour -ne 12 ]; then
        echo "Hour: $hour"
        minute=1
        while [ $minute -le 59 ]; do
            echo $minute
            minute=$((minute + 1))
        done
    else
        echo "Hour: $hour"
    fi
    hour=$((hour + 1))
done

