#!/usr/bin/env bash
# Script to manage the background process manage_my_process

case "$1" in
  start)
    /tmp/manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    if [ -f /var/run/my_process.pid ]; then
      kill "$(cat /var/run/my_process.pid)"
      rm /var/run/my_process.pid
      echo "manage_my_process stopped"
    fi
    ;;
  restart)
    if [ -f /var/run/my_process.pid ]; then
      kill "$(cat /var/run/my_process.pid)"
      rm /var/run/my_process.pid
    fi
    /tmp/manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac

