#!/usr/bin/env bash
# This script prints "To infinity and beyond" every 2 seconds and prints "I am invincible!!!" when receiving SIGTERM

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

